# Generated by Django 5.2.17 on 2026-09-02 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residuos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='endereço de retirada')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='data preferencial')),
                ('period', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], default='MANHA', max_length=20, verbose_name='período')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('ANALISE', 'Em análise'), ('APROVADA', 'Aprovada'), ('AGENDADA', 'Coleta agendada'), ('ANDAMENTO', 'Em coleta'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_collections', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_requests', to=settings.AUTH_USER_MODEL)),
                ('wastes', models.ManyToManyField(related_name='collection_requests', to='residuos.electronicwaste')),
            ],
            options={
                'verbose_name': 'solicitação de coleta',
                'verbose_name_plural': 'solicitações de coleta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('SOLICITADA', 'Solicitada'), ('ANALISE', 'Em análise'), ('APROVADA', 'Aprovada'), ('AGENDADA', 'Coleta agendada'), ('ANDAMENTO', 'Em coleta'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], max_length=20)),
                ('new_status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('ANALISE', 'Em análise'), ('APROVADA', 'Aprovada'), ('AGENDADA', 'Coleta agendada'), ('ANDAMENTO', 'Em coleta'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='coletas.collectionrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DestinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255, verbose_name='destino final')),
                ('destination_date', models.DateField(verbose_name='data da destinação')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='coletas.collectionrequest')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
