# Generated by Django 5.2.17 on 2026-09-04 18:31

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cpf_cnpj_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[apps.accounts.validators.validate_cpf_cnpj], verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
    ]
