# Generated by Django 5.2.17 on 2026-09-02 16:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=150, verbose_name='equipamento')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='fabricante/marca')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='número de série')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='peso estimado (kg)')),
                ('condition', models.CharField(choices=[('FUNCIONANDO', 'Funcionando'), ('PARCIAL', 'Funcionamento parcial'), ('DANIFICADO', 'Danificado'), ('INUTILIZAVEL', 'Sem funcionamento')], max_length=20, verbose_name='estado')),
                ('image', models.ImageField(blank=True, null=True, upload_to='residuos/%Y/%m/', verbose_name='imagem')),
                ('collected', models.BooleanField(default=False, verbose_name='coletado/destinado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wastes', to='residuos.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resíduo eletrônico',
                'verbose_name_plural': 'resíduos eletrônicos',
                'ordering': ['-created_at'],
            },
        ),
    ]
