# Generated by Django 5.2.17 on 2026-09-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropoffPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('address', models.CharField(max_length=255, verbose_name='endereço')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('opening_hours', models.CharField(max_length=150, verbose_name='horário de funcionamento')),
                ('responsible', models.CharField(blank=True, max_length=150, verbose_name='responsável')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ponto de entrega',
                'verbose_name_plural': 'pontos de entrega',
                'ordering': ['name'],
            },
        ),
    ]
